### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by RobinEke** [milasudril/snowflake-toolkit#3]
Robin här.

Jag får följande felmedelande vid kompilering:

> (i) K�r g++ "solid_writer_prototype.cpp" -fpic -march=native -O2 -DNDEBUG -Wall -c -std=c++11 -o "__wand_targets/solid_writer_prototype.o"
> solid_writer_prototype.cpp: In member function 'void SnowflakeModel::SolidWriterPrototype::write(const SnowflakeModel::Solid&)':
> solid_writer_prototype.cpp:49:29: error: 'const class SnowflakeModel::VolumeConvex::Face' has no member named 'm_visible'
>      r_dest.printf("%s)\n",f.m_visible?"outside":"inside");
>                              ^
> (x) Det gick inte att skapa m�let "solid_writer_prototype.o". Kompilatorn returnerade statuskod 1.

**Comment by milasudril** [comment]
Issue should be fixed now. Forgot to update a file.
