### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by RobinEke** [milasudril/snowflake-toolkit#4]
Felmeddelandet verkar uppstå för flera .ice-filer och oberoende av input options.

> robin@dioptase:~/Software/snowflake-toolkit/snowflake-toolkit/code/__wand_targets$ ./snowflake_simulate3 --shape=../../crystal-prototypes/bullet.ice --param-show
> # Loading ../../crystal-prototypes/bullet.ice
> Segmentation fault

**Comment by milasudril** [comment]
Need to add face before tagging it with inside/outside.
