### ISSUE TITLE
Förslag på tillägg

### ISSUE THREAD

**Issue by RobinEke** [milasudril/snowflake-toolkit#5]
Jag är intresserad utav två saker.
1. Volym på genererade aggregat (från simulate3). Som jag ser det löses detta på flera sätt:

--dump-stats ger information om volym på enskilda partiklar, men det finns ingen information om vilken .ice-fil som denna volym svarar mot. En extra kolumn med namn på motsvarande .ice-filen hade löst detta.

Annars hade det varit praktiskt om snowflake_generate eller snowflake_prototype-test, som output kunde ge beräknad volym, antingen i stdout eller som kommenterad text i den skapade .adda-filen.

**Comment by milasudril** [comment]
Volymen kan fås från filnamnet. Om filen heter mesh-_x_.ice så kan volymen hittas på motsvarande rad i filen frame-_N_.txt, där _N_ är det totala antalet iterationer. Detta kräver att statistik för den sista ramen sparas, vilket är fixat nu. Tänk på att _x_ anges i hexadecimal notation.
