### ISSUE TITLE
Problem with prototype-choices and bullet

### ISSUE THREAD

**Issue by RobinEke** [milasudril/snowflake-toolkit#82]
There seems to be a problem related to the --prototype-choices option of simulate3. In the attached choice-file, a bullet with t="0" result in an abortion (see output below). Setting t="0.00000000001" removes this error. It's also fixed if crystal is changed to a hollow.

[choices_2016-12-30_12-00-28-334246224.json.zip](https://github.com/milasudril/snowflake-toolkit/files/678621/choices_2016-12-30_12-00-28-334246224.json.zip)

cmd:

    'snowflake_simulate3'  '--stop-cond=infinity' '--prototype-choices=choices_2016-12-30_12-00-28-334246224.json' '--output-dir=./'

out:

    # Loading choices_2016-12-30_12-00-28-334246224.json
    # Loading ./bullet.ice
    # Initializing
    Parameters:

    Prototype:         
    Prototype choices: choices_2016-12-30_12-00-28-334246224.json
    Seed:              1483100080
    N:                 1023
    droprate:          100
    growthrate:        100
    meltrate:          100
    overlap range:     [0, 0]
    merge retries:     0
    # Simulation started at 2016-12-30 12:14:40
    # 0% done. Cs: 0. Cr: 0. B: 0. M: 0. D: 0. Matrix Fill ratio 0%   # WARNING: No match
    Aborted (core dumped)

**Comment by milasudril** [comment]
Because the gamma distribution must have an expected value greater than zero. Do not use gamma with expected value equal zero.
